getwd()
pwrDS <- read.table("household_power_consumption.txt",skip=1,sep=";")
head(pwrDS)
names(pwrDS) <- c("date","time","global_active_power","global_reactive_power","voltage","global_intensity","sub_metering_1","sub_metering_2","sub_metering_3")
theDS <- subset(pwrDS,pwrDS$date=="1/2/2007" | pwrDS$date =="2/2/2007")
head(theDS)
table(theDS$date)
hist(as.numeric(as.character(theDS$global_active_power)),col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
title(main = "Global Active Power")
dev.copy(png , file = "plot1.png")
dev.off()
