getwd()
pwrDS <- read.table("household_power_consumption.txt",skip=1,sep=";")
head(pwrDS)
names(pwrDS) <- c("date","time","global_active_power","global_reactive_power","voltage","global_intensity","sub_metering_1","sub_metering_2","sub_metering_3")
theDS <- subset(pwrDS,pwrDS$date=="1/2/2007" | pwrDS$date =="2/2/2007")
head(theDS)
table(theDS$date)
theDS$date <- as.Date(theDS$date,format="%d/%m/%Y")
theDS$time <- strptime(theDS$time, format="%H:%M:%S")
head(theDS)
theDS[1:1440,"time"] <- format(theDS[1:1440,"time"],"2007-02-01 %H:%M:%S")
theDS[1441:2880,"time"] <- format(theDS[1441:2880,"time"],"2007-02-02 %H:%M:%S")
par(mfrow=c(2,2))
with(theDS , plot (theDS$time, as.numeric(as.character(theDS$global_active_power)), type = "l", xlab = "" , ylab = "Global Active Power (kilowatts)"))
with (theDS , plot(theDS$time,as.numeric(as.character(theDS$voltage)), type="l",xlab="datetime",ylab="voltage"))
with (theDS , { plot(theDS$time, theDS$sub_metering_1, type = "n", xlab = "" , ylab = "Energy sub metering")
  with(theDS,lines(time,as.numeric(as.character(sub_metering_1))))
  with(theDS,lines(time,as.numeric(as.character(sub_metering_2))), col = "red")
  with(theDS,lines(time,as.numeric(as.character(sub_metering_3)), col = "blue"))
  legend("topright", lty=1, col=c("black","red","blue"),legend=c("sub_metering_1","sub_meering_2","sub_metering_3"))
   })
with(theDS, plot(theDS$time,as.numeric(theDS$global_reactive_power), type = "l", xlab = "datetime" , ylab = "Global Reactive Power"))
dev.copy(png , file = "plot4.png")
dev.off()



